import {useEffect,useState} from "react";import {useLocalSearchParams} from "expo-router";import {ScrollView,View,Text,TextInput,Pressable,StyleSheet} from "react-native";import {createSupabaseClient} from "@huambo-online/supabase";import {listConversations,listMessages,sendMessage,markConversationRead,subscribeToConversationMessages,subscribeToUserConversationMessages,conversationFromParticipantRow,isConversationUnread} from "@huambo-online/core";
const url=process.env.EXPO_PUBLIC_SUPABASE_URL??"";const key=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"";
export default function Mensagens(){const {conversation}=useLocalSearchParams<{conversation?:string}>();const [items,setItems]=useState<any[]>([]);const [previews,setPreviews]=useState<Record<string,any>>({});const [selected,setSelected]=useState<any>(null);const [msgs,setMsgs]=useState<any[]>([]);const [uid,setUid]=useState("");const [body,setBody]=useState("");
async function load(){const c=createSupabaseClient(url,key);const u=await c.auth.getUser();if(!u.data.user)return;setUid(u.data.user.id);const r=await listConversations(c,u.data.user.id);const rows=r.data??[];setItems(rows);const pv:any={};for(const row of rows){const x=conversationFromParticipantRow(row);const z=await listMessages(c,x.id);pv[x.id]=z.data?.at(-1)??null;}setPreviews(pv);}
async function open(x:any){setSelected(x);const c=createSupabaseClient(url,key);const r=await listMessages(c,x.id);setMsgs(r.data??[]);if(uid)await markConversationRead(c,x.id,uid);}
useEffect(()=>{void load();},[]);
useEffect(()=>{if(!uid)return;const c=createSupabaseClient(url,key);return subscribeToUserConversationMessages(c,uid,()=>{void load();});},[uid]);
useEffect(()=>{if(conversation&&items.length){const x=items.find(v=>v.id===conversation);if(x)void open(x);}},[conversation,items.length]);
useEffect(()=>{if(!selected)return;const c=createSupabaseClient(url,key);return subscribeToConversationMessages(c,selected.id,async()=>{const r=await listMessages(c,selected.id);setMsgs(r.data??[]);});},[selected?.id]);
async function send(){if(!body.trim()||!selected||!uid)return;const c=createSupabaseClient(url,key);await sendMessage(c,selected.id,uid,body);setBody("");}
return <ScrollView contentContainerStyle={s.container}><Text style={s.title}>Mensagens</Text>{!selected?items.map(row=>{const x=conversationFromParticipantRow(row);const last=previews[x.id];const unread=isConversationUnread(row,last,uid);return <Pressable key={x.id} onPress={()=>open(x)} style={s.item}><Text style={unread?s.unread:s.bold}>{x.subject||"Conversa"}</Text><Text>{x.context_type}</Text><Text>{last?.body?.slice(0,90)||"Sem mensagens"}</Text>{unread&&<Text>● Não lida</Text>}</Pressable>}):<View><Pressable onPress={()=>setSelected(null)}><Text>← Conversas</Text></Pressable>{msgs.map(m=><Text key={m.id} style={s.msg}>{m.sender_id===uid?"Você":"Utilizador"}: {m.body}</Text>)}<TextInput value={body} onChangeText={setBody} placeholder="Escreva uma mensagem" style={s.input}/><Pressable onPress={send}><Text>Enviar</Text></Pressable></View>}</ScrollView>}
const s=StyleSheet.create({container:{padding:24,gap:16},title:{fontSize:30,fontWeight:"800"},item:{borderWidth:1,borderColor:"#ddd",padding:16,borderRadius:12},bold:{fontWeight:"800"},unread:{fontWeight:"900"},msg:{paddingVertical:8},input:{borderWidth:1,borderColor:"#ccc",padding:12,minHeight:80}});